version: '3'

services:
###> doctrine/doctrine-bundle ###
#  database:
#    image: postgres:${POSTGRES_VERSION:-15}-alpine
#    environment:
#      POSTGRES_DB: ${POSTGRES_DB:-app}
#      # You should definitely change the password in production
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
#      POSTGRES_USER: ${POSTGRES_USER:-app}
#    ports:
#      - "5432:5432"
#    volumes:
#      - database_data:/var/lib/postgresql/data:rw

  database:
    image: mariadb:10.3.34
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-guidebook}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
    volumes:
      - database_data:/var/lib/mariadb/data:rw
    ports:
      - "3306:3306"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
